{% set name = "jupyter_plz" %}
{% set version = "0.1.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 1dc1afd5a4ab6d363746ffc735c48bf12e53c8dcbaa13adabd90b68b7cce3e1a

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - notebook
    - python >=3.6

test:
  imports:
    - jupyter_plz

about:
  home: "https://github.com/akramz/jupyter_plz"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A ChatGPT front-end for Jupyter notebooks (Copilot for Jupyter notebooks)."
  doc_url:
  dev_url: https://github.com/Akramz/jupyter_plz

extra:
  recipe-maintainers:
    - akramz
